# The Docker image that will be used to build your app
image: ubuntu:24.04
pages:
  script:
    - mkdir public
    - mv pkg public
    - mv index.html public
    - mv series_config.json public
    - mv style1.css public
    - mv img public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
