[package]
name = "wasm_dcdc"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
plotters = "0.3.7"
plotters-canvas = "0.3.0"
web-sys = {version="0.3.70",features=["HtmlCanvasElement", "console"]}

[lib]
crate-type = ["cdylib", "rlib"]