/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_chart_free: (a: number, b: number) => void;
export const __wbg_point_free: (a: number, b: number) => void;
export const __wbg_get_point_x: (a: number) => number;
export const __wbg_set_point_x: (a: number, b: number) => void;
export const __wbg_get_point_y: (a: number) => number;
export const __wbg_set_point_y: (a: number, b: number) => void;
export const __wbg_wasmdccalresult_free: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_ontime: (a: number) => number;
export const __wbg_set_wasmdccalresult_ontime: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_dil_on: (a: number) => number;
export const __wbg_set_wasmdccalresult_dil_on: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_dil_off: (a: number) => number;
export const __wbg_set_wasmdccalresult_dil_off: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_current_top: (a: number) => number;
export const __wbg_set_wasmdccalresult_current_top: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_current_bottom: (a: number) => number;
export const __wbg_set_wasmdccalresult_current_bottom: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_intercept_on: (a: number) => number;
export const __wbg_set_wasmdccalresult_intercept_on: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_intercept_off: (a: number) => number;
export const __wbg_set_wasmdccalresult_intercept_off: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_ro: (a: number) => number;
export const __wbg_set_wasmdccalresult_ro: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_rfb1: (a: number) => number;
export const __wbg_set_wasmdccalresult_rfb1: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_fz: (a: number) => number;
export const __wbg_set_wasmdccalresult_fz: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_cfb: (a: number) => number;
export const __wbg_set_wasmdccalresult_cfb: (a: number, b: number) => void;
export const __wbg_get_wasmdccalresult_dvout: (a: number) => number;
export const __wbg_set_wasmdccalresult_dvout: (a: number, b: number) => void;
export const wasmdccalresult_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => number;
export const wasm_dccal_result: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const chart_coil_current: (a: any, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number];
export const __wbg_get_wasmdccalresult_duty: (a: number) => number;
export const __wbg_get_wasmdccalresult_period: (a: number) => number;
export const __wbg_set_wasmdccalresult_duty: (a: number, b: number) => void;
export const __wbg_set_wasmdccalresult_period: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
